Plumbago_Brokerage/Pages/KPIManager/IssueBatchKPI.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Plumbago_Brokerage.Pages.KPIManager
{
    public class IssueBatchKPIModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Plumbago_Brokerage/Pages/KPIManager/IssueEmployeeKPI.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.ViewComponents;
using PlumbagoHR.Data.Repository;

namespace Plumbago_Brokerage.Pages.KPIManager
{
    public class IssueEmployeeKPIModel : PageModel
    {

        [BindProperty(SupportsGet = true)]
        public SearchFilterModel Searchfilter { get; set; }
        [BindProperty(SupportsGet = true)]
        public TableListVM TableList { get; set; }
        [BindProperty]
        public List<int> SelectedIDs { get; set; }
        public string ErrMsg { get; set; }

        public string ErrMsgType { get; set; }

        public void OnGet()
        {
            var mod = new ModMain();
            Searchfilter.Groupname = "KPM_Issue";
            TableList.Groupname = "KPM_Issue";
            Searchfilter.Branches = mod.PopulateBranches();
            Searchfilter.Departments = mod.PopulateDepartments();
            TableList.Employees = new EmployeesRepo().GetEmployeesBySearchFilter(Searchfilter);
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("IssueEmployeeKPI", new { Searchfilter.From, Searchfilter.To, Searchfilter.Contains, Searchfilter.Option });
        }

        public IActionResult OnPostPrint()
        {
            ModMain mod = new ModMain();
            var kpirepo = new KPIRepo();
            if (SelectedIDs.Count == 0)
            {
                TempData["error"] = true;
                TempData["message"] = "Select an Employee first";
               
                Searchfilter.Groupname = "KPM_Issue";
                TableList.Groupname = "KPM_Issue";
                Searchfilter.Branches = mod.PopulateBranches();
                Searchfilter.Departments = mod.PopulateDepartments();
                TableList.Employees = new EmployeesRepo().GetEmployeesBySearchFilter(Searchfilter);
                return Page();
            }
            foreach (var id in SelectedIDs)
            {
                
            }
            TempData["success"] = true;
            TempData["message"] = mod.GetSuccessMessage();
            return RedirectToPage("IssueEmployeeKPI");
        }
    }
}

Plumbago_Brokerage/Pages/KPIManager/KPIs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.ViewComponents;

namespace Plumbago_Brokerage.Pages.KPIManager
{
    public class KPIsModel : PageModel
    {

        [BindProperty(SupportsGet = true)]
        public SearchFilterModel Searchfilter { get; set; }
        [BindProperty(SupportsGet = true)]
        public TableListVM TableList { get; set; }

        public void OnGet()
        {
            var mod = new ModMain();
            Searchfilter.Groupname = "KPM_kpi";
            TableList.Groupname = "KPM_kpi";
            Searchfilter.Departments = mod.PopulateDepartments();
            Searchfilter.Periods = mod.PopulatePeriod();
            TableList.Kpis = new KPIRepo().GetKPIBySearchFilter(Searchfilter);
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("KPIs", new { Searchfilter.From, Searchfilter.To, Searchfilter.Period, Searchfilter.Department });
        }
    }
}

Plumbago_Brokerage/Pages/KPIManager/KPIs_Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.Models;
using Plumbago_Brokerage.ViewComponents;

namespace Plumbago_Brokerage.Pages.KPIManager
{
    [BindProperties]
    public class KPIs_EditModel : PageModel
    {
        public int Id { get; set; }
        public string Department { get; set; }
        public string Period { get; set; }
        public string KpiContent { get; set; }
        public IEnumerable<SelectListItem> Periods { get; set; }
        public IEnumerable<SelectListItem> Departments { get; set; }
        [BindProperty(SupportsGet = true)]
        public PageEditModel EditModel { get; set; }
        private readonly IMapper _Mapper;

        public KPIs_EditModel(IMapper Mapper)
        {
            _Mapper = Mapper;
        }
        public IActionResult OnGet(int? id)
        {
            var mod = new ModMain();
            if (id != null)
            {
                var kpirepo = new KPIRepo().GetKPIByID(id);
                _Mapper.Map(kpirepo, this);
                Periods = mod.PopulatePeriod();
                Departments = mod.PopulateDepartments();
                EditModel.PageTitle = $"Edit KPI {id}";
                return Page();
            }
            EditModel.PageTitle = "Create New KPI";          
            Periods = mod.PopulatePeriod();
            Departments = mod.PopulateDepartments();
            return Page();
        }

        public IActionResult OnPostSave()
        {
            if (!ModelState.IsValid) return Page();
            if (DoInsert())
            {
                return RedirectToPage("KPIs");
            }
            else
            {
                return Page();
            }
        }

        private bool DoInsert()
        {
            ModMain mod = new ModMain();
            var kpirepo = new KPIRepo();
            if (Id > 0)
            {
                //update
                var kpi = kpirepo.GetKPIByID(Id);                
                _Mapper.Map(this, kpi);

                int result = kpirepo.UpdateKPI(kpi, HttpContext.Session.GetString("Curruser"));
                if (result > 0)
                {
                    TempData["success"] = true;
                    TempData["message"] = mod.GetSuccessMessage();
                    return true;
                }
                else
                {
                    EditModel.ErrMsg = mod.GetErrorMessage();
                    return false;
                }
            }
            else
            {
                Kpi kpi = new Kpi();              
                _Mapper.Map(this, kpi);
                int result = kpirepo.CreateKPI(kpi, HttpContext.Session.GetString("Curruser"));
                if (result > 0)
                {
                    TempData["success"] = true;
                    TempData["message"] = mod.GetSuccessMessage();
                    return true;
                }
                else
                {
                    EditModel.ErrMsg = mod.GetErrorMessage();
                    return false;
                }


            }
        }

    }
}

Plumbago_Brokerage/Pages/KPIManager/IssueBatchKPI.cshtml
@page
@model Plumbago_Brokerage.Pages.KPIManager.IssueBatchKPIModel
@{
}

Plumbago_Brokerage/Pages/KPIManager/IssueEmployeeKPI.cshtml
@page
@model Plumbago_Brokerage.Pages.KPIManager.IssueEmployeeKPIModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
            Issue Employee KPI
        </h3>

    </div>

    <hr />
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />

        <a class="button primary showloading" href="/KPIManager/KPIs_Edit"> Create New</a>
        <button type="submit" class="button showloading primary" asp-page-handler="Print"><i class="fas fa-trash"></i> Print Employee KPI</button>
        <button type="submit" class="button showloading secondary" onclick="return confirm('Are you sure you want to mail KPI to all Employees?')" asp-page-handler="Mail"><i class="fas fa-envelope"></i> Mail Employees KPI</button>
        <a class="button alert" onclick="goBack()">Cancel</a>
        <button type="submit" class="button showloading alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>

    </div>
</form>

Plumbago_Brokerage/Pages/KPIManager/KPIs.cshtml
@page
@model Plumbago_Brokerage.Pages.KPIManager.KPIsModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
            KPIs
        </h3>

    </div>

    <hr />
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />

        <a class="button alert" onclick="goBack()">Cancel</a> <a class="button primary showloading" href="/KPIManager/KPIs_Edit"> Create New</a>

        <button type="submit" class="button showloading alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>
    </div>
</form>

Plumbago_Brokerage/Pages/KPIManager/KPIs_Edit.cshtml
@page
@model Plumbago_Brokerage.Pages.KPIManager.KPIs_EditModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
            @Model.EditModel.PageTitle
        </h3>

    </div>
    <hr />
    @if (Model.EditModel.ErrMsg != null)
    {
        ViewData["message"] = Model.EditModel.ErrMsg;
        ViewData["type"] = Model.EditModel.ErrMsgType;
        <partial name="_messagepanelPartial" />
    }
</div>


<div class="border-none" data-cls-panel="rounded" data-role="panel">
    <form id="myform" method="post">


        <div class="container-fluid">
            <div class="row">
                <div class="cell-12">

                    <div class="mb-3" data-role="accordion"
                         data-one-frame="false"
                         data-show-active="true">

                        <div class="frame active">
                            <div class="heading">KPI Details</div>
                            <div class="content">
                                <div class="p-2">

                                    <div class="row mb-3">
                                        <label class="text-small text-bold cell-sm-1">Department</label>
                                        <div class="cell-sm-4">
                                            <select asp-for="Department" asp-items="Model.Departments" class="rounded text-small" data-role="select">
                                                <option disabled value="">- select -</option>

                                            </select>
                                            <span class="text-small fg-red" asp-validation-for="Department"></span>
                                        </div>
                                        <div class="cell-sm-1"></div>
                                        <label class="text-small text-bold cell-sm-1">Period</label>
                                        <div class="cell-sm-4">
                                            <select asp-for="Period" asp-items="Model.Periods" class="rounded text-small" data-role="select">
                                                <option disabled value="">- select -</option>

                                            </select>
                                        </div>
                                        <span class="text-small fg-red" asp-validation-for="Period"></span>
                                    </div>
                                    <br />
                                    <div class="row mb-3">
                                        <textarea asp-for="KpiContent" id="editor1"></textarea>
                                        <span class="text-small fg-red" asp-validation-for="KpiContent"></span>
                                    </div>

                                    <div class="form-group">

                                        <div class="text-center">
                                            <span class="">
                                                <a class="button alert" onclick="goBack()">Cancel</a>  <button type="submit" class="button primary" asp-page-handler="Save"> <i class="fas fa-save"></i> Submit</button>
                                            </span>

                                        </div>


                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>




                </div>


            </div>

            <div>


            </div>

        </div>
    </form>

</div>
<style>

    .cke_chrome {
        width: 100% !important;
    }
</style>

<script>
    CKEDITOR.replace('editor1', {
        height: 800,
        
        baseFloatZIndex: 10005
    });
</script>