Plumbago_Brokerage/Pages/HumanResources/EmployeeAppraisals.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Plumbago_Brokerage.Pages.HumanResources
{
    public class EmployeeAppraisalsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Plumbago_Brokerage/Pages/HumanResources/EmployeeCompensation_Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Plumbago_Brokerage.Pages.HumanResources
{
    public class EmployeeCompensation_EditModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Plumbago_Brokerage/Pages/HumanResources/EmployeeDocuments_Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.ViewComponents;

namespace Plumbago_Brokerage.Pages.HumanResources
{
    public class EmployeeDocuments_EditModel : PageModel
    {
        public int DocumentId { get; set; }
        public string EmployeeId { get; set; }
        public string DocumentType { get; set; }
        public string DocumentPath { get; set; }
     
        [BindProperty(SupportsGet = true)]
        public PageEditModel EditModel { get; set; }
        [BindProperty(SupportsGet = true)]
        public TableListVM TableList { get; set; }
        private readonly IMapper _Mapper;

        public EmployeeDocuments_EditModel(IMapper Mapper)
        {
            _Mapper = Mapper;
        }
        public IActionResult OnGet(int? id, int? detailid)
        {
            var mod = new ModMain();
            var DocRepo = new DocumentsRepo();
            EditModel.Groupname = "hr_employees";
            EditModel.Editid = id.ToString();
            TableList.Groupname = "hr_documents_edit";
            TableList.Documents = DocRepo.GetAllEmployeeDocuments(id.ToString());
           
            EditModel.PageTitle = "Add new Employee Documents";
            return Page();
        }
    }
}

Plumbago_Brokerage/Pages/HumanResources/EmployeeGradeLevel_Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.ViewComponents;

namespace Plumbago_Brokerage.Pages.HumanResources
{
    public class EmployeeGradeLevel_EditModel : PageModel
    {
        public long PromotionId { get; set; }
        public int? SheetId { get; set; }
        public string EmployeeId { get; set; }
        public string Grade { get; set; }
        public string Step { get; set; }
        public DateTime? ProDate { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? Bs { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? Ha { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? Ta { get; set; }
        public decimal? Ygpay { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? Ytax { get; set; }
        public string TransStatus { get; set; }
        public string TransGuid { get; set; }
        public string Remarks { get; set; }
        [BindProperty(SupportsGet = true)]
        public PageEditModel EditModel { get; set; }
        [BindProperty(SupportsGet = true)]
        public TableListVM TableList { get; set; }
        public IEnumerable<SelectListItem> Grades { get; set; }
        public IEnumerable<SelectListItem> Paysheets { get; set; }

        private readonly IMapper _Mapper;

        public EmployeeGradeLevel_EditModel(IMapper Mapper)
        {
            _Mapper = Mapper;
        }
        public IActionResult OnGet(int? id, int? detailid)
        {
            //for toptabs
            var mod = new ModMain();
            var PromotionRepo = new PromotionRepo();
            EditModel.Groupname = "hr_employees";
            EditModel.Editid = id.ToString();
            TableList.Groupname = "hr_EmployeeGradeLevel_Edit";
            TableList.Promotions = PromotionRepo.GetEmployeePromotions(id.ToString());
            if (id != null)
            {
                //fetch employee top hobbies
               
                Grades = mod.PopulateGradeLevel();
                Paysheets = mod.PopulatePaySheets();
                EmployeeId = id.ToString();
                //If detail id is not empty then load the edit data
                if (detailid != null)
                {
                    var promotions = PromotionRepo.GetPromotionByEmployeeIDandEditID(id.ToString(), (long)detailid);
                    _Mapper.Map(promotions, this);
                    Grades = mod.PopulateGradeLevel();
                    Paysheets = mod.PopulatePaySheets();
                    EditModel.PageTitle = $"Edit Employee Promotions: {id} and Detail: { detailid}";
                }
                else
                {
                    EditModel.PageTitle = $"Edit Employee Promotions: {id}";
                }

                return Page();
            }
            Grades = mod.PopulateGradeLevel();
            Paysheets = mod.PopulatePaySheets();
            EditModel.PageTitle = "Add new Employee Promotion and Grade Level";
            return Page();
        }
    }
}

Plumbago_Brokerage/Pages/HumanResources/EmployeeMedicalProcessing.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.ViewComponents;

namespace Plumbago_Brokerage.Pages.HumanResources
{
    public class EmployeeMedicalProcessingModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public SearchFilterModel Searchfilter { get; set; }
        [BindProperty(SupportsGet = true)]
        public TableListVM TableList { get; set; }
        [BindProperty]
        public List<int> SelectedIDs { get; set; }
        public void OnGet()
        {
            var mod = new ModMain();
            Searchfilter.Groupname = "hr_employee_medicalprocessing";
            TableList.Groupname = "hr_employee_medicalprocessing";
            TableList.MedicalsQueryable = new MedicalRepo().GetMedicalActivitiesBySearchFilter(Searchfilter);
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("EmployeeMedicalProcessing", new { Searchfilter.From, Searchfilter.To, Searchfilter.Contains, Searchfilter.Option });
        }

        public IActionResult OnPostApprove(List<int> SelectedIDs)
        {
            ModMain mod = new ModMain();
            //var leaverepo = new LeaveRepo();
            //foreach (var item in SelectedIDs)
            //{
            //    leaverepo.DeleteLeaveByID(item);
            //}
            TempData["success"] = true;
            TempData["message"] = mod.GetDeletedMessage();
            return RedirectToPage("EmployeeMedicalProcessing");

        }
    }
}

Plumbago_Brokerage/Pages/HumanResources/Employees_edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Plumbago_Brokerage.Data;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.Models;
using Plumbago_Brokerage.ViewComponents;
using PlumbagoHR.Data.Repository;

namespace Plumbago_Brokerage.Pages.HumanResources
{
    [BindProperties]
    public class Employees_editModel : PageModel
    {
        public string EmployeeId { get; set; }
        [Required]
        public string Username { get; set; }
        public string StaffIdno { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public string OtherNames { get; set; }
        public string Address { get; set; }
        [Required]
        public string State { get; set; }
       
        public string Country { get; set; }
        [Required]
        public string Sex { get; set; }
        [Required]
        public DateTime? BirthDate { get; set; } = DateTime.Now;
        [Required]
        public string MaritalStatus { get; set; }
        [Required]
        public string StateOrigin { get; set; }
        public string NationalIdno { get; set; }

        public string AcctNo1 { get; set; }

        public string AcctName1 { get; set; }
        public string AcctNo2 { get; set; }
        public string AcctName2 { get; set; }
        public string BranchId { get; set; }
        public string Branch { get; set; }

        public string DeptId { get; set; }
        public string Paysheet { get; set; }
        public string Dept { get; set; }
    
        public string UnitId { get; set; }
        public string Unit { get; set; }
       
        public long? GradeId { get; set; }
        public string Grade { get; set; }
        public DateTime? HireDate { get; set; } = DateTime.Now;
        public string Telephone { get; set; }
        [Required]
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string NextKin { get; set; }
        public string KinAddress { get; set; }
        public string KinPhone { get; set; }
        public string KinRelationship { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public long? Smoker { get; set; }
        public string DisableType { get; set; }
        public string Remarks { get; set; }
        public string Step { get; set; }
        public string Tag { get; set; }
        public string PayFirstMonth { get; set; }
        public long? SheetId2 { get; set; }
        public string ConfirmStatus { get; set; }
        public long? ConfirmDuration { get; set; }
        public DateTime? ConfirmationDate { get; set; } = DateTime.Now;
        public DateTime? RetiredDate { get; set; }
        public byte? Deleted { get; set; }
        public byte? Active { get; set; }
        public string Hmoname { get; set; }
        public string Hmoid { get; set; }
        public string Email2 { get; set; }
        [Required]
        public string PrimaryManager { get; set; }
        public string PrimaryManagerId { get; set; }
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? AnnualTax { get; set; } = 0;
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? BasicSalary { get; set; } = 0;
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? TransportAllowance { get; set; } = 0;
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? HousingAllowance { get; set; } = 0;
        public IEnumerable<SelectListItem> Employees { get; set; }
        [DataType(DataType.Upload)]
        public IFormFile Image { get; set; }
        public string ImageUrl { get; set; }
        public IEnumerable<SelectListItem> States { get; set; }
        public IEnumerable<SelectListItem> HMOLists { get; set; }
        public IEnumerable<SelectListItem> PFALists { get; set; }
        public IEnumerable<SelectListItem> Paygroups { get; set; }
        public IEnumerable<SelectListItem> GradeLevel { get; set; }
        public IEnumerable<SelectListItem> Departments { get; set; }
        public IEnumerable<SelectListItem> Steps { get; set; }
    
        public IEnumerable<SelectListItem> Units { get; set; }
        public IEnumerable<SelectListItem> Branches { get; set; }
        public IEnumerable<SelectListItem> banks { get; set; }
        public string[] ConfirmStatuses = new[] { "Active", "Resigned", "Suspended", "Retired" };
        [BindProperty(SupportsGet = true)]
        public PageEditModel EditModel { get; set; }
        public string ErrMsg { get; set; }
        public string ErrMsgType { get; set; }

        private readonly IMapper _Mapper;

        private readonly IWebHostEnvironment _environment;
        public Employees_editModel(IMapper Mapper, IWebHostEnvironment environment)
        {
            _Mapper = Mapper;
            _environment = environment;
        }


        public IActionResult OnGet(int? id)
        {
            //for toptabs
            EditModel.Groupname = "hr_employees";
            EditModel.Editid = id.ToString();
            var mod = new ModMain();
            if (id != null)
            {

                var employee = new EmployeesRepo().GetEmployeeByID(id.ToString());
                ImageUrl = employee.Image;
            
                _Mapper.Map(employee, this);
                EditModel.PageTitle = $"Edit Employee: {Surname} {OtherNames}";
                States = mod.PopulateStates();
                HMOLists = mod.PopulateHMO();
                PFALists = mod.PopulatePFA();
                Paygroups = mod.PopulatePaySheets();
                GradeLevel = mod.PopulateGradeLevel();
                Departments = mod.PopulateDepartments();
                Units = mod.PopulateUnits();
                Branches = mod.PopulateBranches();
                Employees = mod.PopulatEmployees();
                Steps = mod.PopulateSteps();
                banks = mod.PopulateBanks();
                return Page();
            }
            States = mod.PopulateStates();
            HMOLists = mod.PopulateHMO();
            PFALists = mod.PopulatePFA();
            Paygroups = mod.PopulatePaySheets();
            GradeLevel = mod.PopulateGradeLevel();
            Departments = mod.PopulateDepartments();
            Units = mod.PopulateUnits();
            Branches = mod.PopulateBranches();
            Employees = mod.PopulatEmployees();
            Steps = mod.PopulateSteps();
            banks = mod.PopulateBanks();
            EditModel.PageTitle = "Create new Employee";
            return Page();
        }

        public IActionResult OnPostSave()
        {
            //if (!ModelState.IsValid)
            //{
            //    return Page();
            //}
            if (DoInsert())
            {
                return RedirectToPage("EmployeeGradeLevel_Edit", new { id = EmployeeId });
            }
            else
            {
                return Page();
            }
        }

        private bool DoInsert()
        {
            ModMain mod = new ModMain();
            var employeerepo = new EmployeesRepo();
            if (EmployeeId != null)
            {
                //update
                var emp = employeerepo.GetEmployeeByID(EmployeeId);
                _Mapper.Map(this, emp);
                emp.Dept = mod.GetDepartmentByID(DeptId);
                emp.Unit = mod.GetUnitByID(UnitId);
                emp.Branch = mod.GetBranchByID(BranchId);
                emp.Grade = mod.GetGradeByID(GradeId.ToString());
                emp.Paysheet = mod.GetPaySheetByID(SheetId2.ToString());
                emp.PrimaryManager = mod.GetEmployeeNameByID(PrimaryManagerId);
                if (Image != null)
                {
                    var filename = $"{Guid.NewGuid()}_{Image.FileName}";
                    var filepath = Path.Combine(_environment.WebRootPath, "Uploads", "Profile", filename);
                   
                    using (var fileStream = new FileStream(filepath, FileMode.Create))
                    {
                        Image.CopyTo(fileStream);
                    }
                    emp.Image = filename;
                }
              
                int result = employeerepo.UpdateEmployee(emp, HttpContext.Session.GetString("Curruser"));
                if (result > 0)
                {
                    TempData["success"] = true;
                    TempData["message"] = mod.GetSuccessMessage();
                    return true;
                }
                else
                {
                    ErrMsg = mod.GetErrorMessage();
                    ErrMsgType = mod.GetErrMessageTypeError();
                    return false;
                }
            }

            else
            {

                //New Record

                Employees emp = new Employees();
                //map rest of data
                _Mapper.Map(this, emp);
                emp.OtherNames = OtherNames.ToUpper();
                emp.Surname = Surname.ToUpper();
                emp.Dept = mod.GetDepartmentByID(DeptId);
                emp.Unit = mod.GetUnitByID(UnitId);
                emp.Branch = mod.GetBranchByID(BranchId);
                emp.Grade = mod.GetGradeByID(GradeId.ToString());

Plumbago_Brokerage/Pages/HumanResources/EmployeeAppraisals.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.EmployeeAppraisalsModel
@{
}

Plumbago_Brokerage/Pages/HumanResources/EmployeeMedicalDetails_Edit.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.EmployeeMedicalDetails_EditModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
            @Model.EditModel.PageTitle
        </h3>

    </div>
    <hr />
    @if (Model.EditModel.ErrMsg != null)
    {
        ViewData["message"] = Model.EditModel.ErrMsg;
        ViewData["type"] = Model.EditModel.ErrMsgType;
        <partial name="_messagepanelPartial" />
    }
</div>
<partial name="TopTabs" model="Model.EditModel" />

<div class="border-none" data-cls-panel="rounded" data-role="panel">
    <form id="myform" method="post">


        <div class="container-fluid">
            <div class="row">
                <div class="cell-12">

                    <div class="mb-3" data-role="accordion"
                         data-one-frame="false"
                         data-show-active="true">

                        <div class="frame active">
                            <div class="heading">Employee Medicals</div>
                            <div class="content">
                                <div class="p-2">
                                    <input type="hidden" asp-for="MedDetailsId" />


                                    <div class="row mb-3">
                                        <label class="text-small text-bold cell-sm-1">Height</label>
                                        <div class="cell-sm-4">

                                            <input data-role="input" data-prepend="<span class='mif-user'></span>" class="form-control text-small rounded" type="text" asp-for="Height"  />

                                        </div>
                                        <div class="cell-sm-1"></div>
                                        <label class="text-small text-bold cell-sm-1">Weight</label>
                                        <div class="cell-sm-4">
                                            <input id="" data-role="input" data-prepend="<span class='mif-user'></span>" class="form-control rounded" type="text" asp-for="Weight" />

                                        </div>

                                    </div>

                                    <div class="row mb-3">
                                        <label class="text-small text-bold cell-sm-1">Blood Group</label>
                                        <div class="cell-sm-4">

                                            <input data-role="input" data-prepend="<span class='mif-user'></span>" class="form-control text-small rounded" type="text" asp-for="Bloodgrp"  />

                                        </div>
                                        <div class="cell-sm-1"></div>
                                        <label class="text-small text-bold cell-sm-1">Genotype</label>
                                        <div class="cell-sm-4">
                                            <input id="" data-role="input" data-prepend="<span class='mif-user'></span>" class="form-control rounded" type="text" asp-for="Type" />

                                        </div>

                                    </div>
                                    <div class="row mb-3">
                                        <label class="text-small text-bold cell-sm-1">Major Allergies</label>
                                        <div class="cell-sm-4">

                                            <textarea asp-for="Allergics" class="metro-input rounded"></textarea>

                                        </div>
                                        <div class="cell-sm-1"></div>
                                        <label class="text-small text-bold cell-sm-1">Genotype</label>
                                        <div class="cell-sm-4">
                                            <textarea asp-for="Type" class="metro-input rounded"></textarea>
                                          
                                        </div>

                                    </div>

                                    <div class="row mb-3">
                                        <label class="text-small text-bold cell-sm-1">Medical Limits</label>
                                        <div class="cell-sm-4">

                                            <input data-role="input" data-prepend="<span class='mif-user'></span>" class="form-control text-small rounded" type="text" asp-for="Medicallimits"  />

                                        </div>
                                        <div class="cell-sm-1"></div>
                                       
                                    </div>



                                    <div class="form-group">

                                        <div class="text-center">
                                            <span class="">
                                                <a class="button alert" onclick="goBack()">Cancel</a>  <button type="submit" class="button primary" asp-page-handler="Save"> <i class="fas fa-save"></i> Submit </button>
                                            </span>

                                        </div>


                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>


                    <div class="mb-3" data-role="accordion"
                         data-one-frame="false"
                         data-show-active="true">

                        <div class="frame active">
                            <div class="heading">Employee Interests</div>
                            <div class="content">
                                <div class="p-2">

                                    <div class="row mb-3">
                                        <div class="cell-sm-12">
                                            <partial name="TableAreaPartial" model="Model.TableList" />
                                        </div>

                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>

                </div>


            </div>

            <div>


            </div>

        </div>
    </form>

</div>

Plumbago_Brokerage/Pages/HumanResources/EmployeeMedicalProcessing.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.EmployeeMedicalProcessingModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
            Employee Medical Activities
        </h3>

    </div>

    <hr />
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />


        <a class="button primary showloading" href="/HumanResources/EmployeeMedicalProcessing_Edit"> Create New</a>
 
        <button type="submit" class="button showloading success" asp-page-handler="Approve"><i class="fas fa-check"></i> Approve</button>
        <button type="submit" class="button showloading alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>
        @*<button type="submit" class="button showloading alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>*@
    </div>
</form>

Plumbago_Brokerage/Pages/HumanResources/EmployeePromotions.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.EmployeePromotionsModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
            Employee Promotions
        </h3>

    </div>

    <hr />
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />

        
      
        @*<button type="submit" class="button showloading alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>*@
    </div>
</form>

Plumbago_Brokerage/Pages/HumanResources/EmployeePromotions_Edit.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.EmployeePromotions_EditModel
@{
}

Plumbago_Brokerage/Pages/HumanResources/EmployeeTrainingProcessing.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.EmployeeTrainingProcessingModel
@{
}

Plumbago_Brokerage/Pages/HumanResources/Employees.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.EmployeesModel
@{
    ViewData["Title"] = "Employees";
}

<div class="container-fluid">
    <div>
        <h3>
            Employees
        </h3>

    </div>

    <hr />
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />

        <a class="button primary showloading" href="/HumanResources/Employees_edit"> Create New</a>

        <button type="submit" class="button showloading alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>
    </div>
    </form>
    

Plumbago_Brokerage/Pages/HumanResources/LeaveCalendar.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.LeaveCalendarModel
@{
}

Plumbago_Brokerage/Pages/HumanResources/LeaveRequestsProcessing.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.LeaveRequestsModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
            Leave Requests Activities
        </h3>

    </div>

    <hr />
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />


        <a class="button primary showloading" href="/HumanResources/EmployeeMedicalProcessing_Edit"> Create New</a>

        <button type="submit" class="button showloading success" asp-page-handler="Approve"><i class="fas fa-check"></i> Approve</button>
       
        <button type="submit" class="button showloading alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>
    </div>
</form>

Plumbago_Brokerage/Pages/HumanResources/LoanRequestsProcessing.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.LoanRequestsModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
            Loan Request PROCESSING
        </h3>

    </div>
    <hr />
    @if (Model.ErrMsg != null)
    {
        ViewData["message"] = Model.ErrMsg;
        ViewData["type"] = Model.ErrMsgType;
        <partial name="_messagepanelPartial" />
    }
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />


        <a class="button primary showloading" href="/HumanResources/LoanRequestsProcessing_Edit"> Create New</a>

        <button type="submit" class="button showloading success" asp-page-handler="Approve"><i class="fas fa-check"></i> Approve</button>

        <button type="submit" class="button showloading alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>
        @*<button type="submit" class="button showloading alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>*@
    </div>
</form>

Plumbago_Brokerage/Pages/HumanResources/ReimbursementRequests.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.ReimbursementRequestsModel
@{
}

Plumbago_Brokerage/Pages/HumanResources/WorkExperiences_Edit.cshtml
@page
@model Plumbago_Brokerage.Pages.HumanResources.WorkExperiences_EditModel
@{
}