Plumbago_Brokerage/Models/Users.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Plumbago_Brokerage.Models
{
    public partial class Users
    {
        public long UserId { get; set; }
        public string EmployeeId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public DateTime? PwdExpiry { get; set; }
        public string SecQuestion { get; set; }
        public string SecAnswer { get; set; }
        public DateTime? LastLoginDate { get; set; }
        public byte? Active { get; set; }
        public string SubmittedBy { get; set; }
        public DateTime? SubmittedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
    }
}

Plumbago_Brokerage/Pages/GeneralSettings/AllowanceRates.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.ViewComponents;
using PlumbagoHR.Data.Repository;

namespace Plumbago_Brokerage.Pages.GeneralSettings
{
    public class AllowanceRatesModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public SearchFilterModel Searchfilter { get; set; }
        [BindProperty(SupportsGet = true)]
        public TableListVM TableList { get; set; }


        public void OnGet()
        {
            var mod = new ModMain();
            Searchfilter.Groupname = "gs_allowancerates";
            TableList.Groupname = "gs_allowancerates";
            Searchfilter.Paysheets = mod.PopulatePaySheets();
            TableList.payAllowances = new PayAllowanceRepo().GetPayAllowanceBySearchFilter(Searchfilter);
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("AllowanceRates", new { Searchfilter.From, Searchfilter.To, Searchfilter.Contains, Searchfilter.Option, Searchfilter.Paysheet });
        }
    }
}

Plumbago_Brokerage/Pages/GeneralSettings/AllowanceRates_Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.Models;
using Plumbago_Brokerage.ViewComponents;

namespace Plumbago_Brokerage.Pages.GeneralSettings
{
    [BindProperties]
    public class AllowanceRates_EditModel : PageModel
    {
        public long Hid { get; set; }
        public long AllowId { get; set; }
        public string AllowName { get; set; }
        public decimal? Value1 { get; set; }
        public decimal? Percentage { get; set; } = 0;
        public string Steps { get; set; }
        public long? GradeId { get; set; }
        public string Grade { get; set; }
        public string Sheet { get; set; }
        public int? SheetId { get; set; }
        public string ErrMsg { get; set; }
        public string ErrMsgType { get; set; }
        public string RateType { get; set; }
        public IEnumerable<SelectListItem> Paysheets { get; set; }
        public IEnumerable<SelectListItem> Allowances { get; set; }
        public IEnumerable<PayAllowance> PayAllowances { get; set; }

        [BindProperty(SupportsGet = true)]
        public PageEditModel EditModel { get; set; }
        private readonly IMapper _Mapper;

        public AllowanceRates_EditModel(IMapper Mapper)
        {
            _Mapper = Mapper;
        }
        public IActionResult OnGet(int? id)
        {
            var mod = new ModMain();
            var repo = new PayAllowanceRepo();
            //var setting = new SettingsRepo().GetCompanySettings();
            if (id != null)
            {

                var allowancerate = repo.GetPayAllowanceByID(id);
              
                _Mapper.Map(allowancerate, this);
                EditModel.PageTitle = $"Edit Allowance Rate: {id}";
                Allowances = mod.PopulateAllowanceIDs();
                Paysheets = mod.PopulatePaySheets();
                PayAllowances = repo.GetAllPayAllowances();
                return Page();
            }
            Allowances = mod.PopulateAllowanceIDs();
            Paysheets = mod.PopulatePaySheets();
            PayAllowances = repo.GetAllPayAllowances();
            EditModel.PageTitle = "Create new Allowance Rate";
            return Page();

        }

        public IActionResult OnPostSaveAndAddNew()
        {
            var mod = new ModMain();
            var repo = new PayAllowanceRepo();
            if (Hid > 0)
            {
                //update
                var rec = new PayAllowanceRepo().GetPayAllowanceByID(Hid);
                _Mapper.Map(this, rec);
                if (RateType == "Percentage")
                {
                    rec.Percentage = Value1;
                    rec.Value1 = 0;
                }
                rec.Sheet = mod.GetPaySheetByID(SheetId.ToString());
                rec.AllowName = mod.GetAllowanceNameByID(AllowId.ToString());

                var res = new PayAllowanceRepo().UpdatePayAllowance(rec, HttpContext.Session.GetString("Curruser"));
                if (res > 0)
                {
                    TempData["success"] = true;
                    TempData["message"] = mod.GetSuccessMessage();
                    Allowances = mod.PopulateAllowanceIDs();
                    Paysheets = mod.PopulatePaySheets();
                    PayAllowances = repo.GetAllPayAllowances();
                    EditModel.PageTitle = "Create new Allowance Rate";
                    return Page();
                }
                ErrMsg = mod.GetErrorMessage();
                ErrMsgType = mod.GetErrMessageTypeError();
                return Page();
            }
            else
            {
                //new record
                var payallowance = new PayAllowance();
                _Mapper.Map(this, payallowance);

                //check if ratetype is percentage. if yes save percentage value and set fixed value to 0 else just save fixed value.
                if (RateType == "Percentage")
                {
                    payallowance.Percentage = Value1;
                    payallowance.Value1 = 0;
                }
                payallowance.Sheet = mod.GetPaySheetByID(SheetId.ToString());
                payallowance.AllowName = mod.GetAllowanceNameByID(AllowId.ToString());
                var res = new PayAllowanceRepo().CreatePayAllowance(payallowance, HttpContext.Session.GetString("Curruser"));
                if (res > 0)
                {
                    TempData["success"] = true;
                    TempData["message"] = mod.GetSuccessMessage();
                    Allowances = mod.PopulateAllowanceIDs();
                    Paysheets = mod.PopulatePaySheets();
                    PayAllowances = repo.GetAllPayAllowances();
                    EditModel.PageTitle = "Create new Allowance Rate";
                    return Page();
                }
                ErrMsg = mod.GetErrorMessage();
                ErrMsgType = mod.GetErrMessageTypeError();
                return Page();
            }

        
        }

        public IActionResult OnPostSubmit()
        {
            var mod = new ModMain();
            if (Hid > 0)
            {
                //update
                var rec = new PayAllowanceRepo().GetPayAllowanceByID(Hid);
                _Mapper.Map(this, rec);
                if (RateType == "Percentage")
                {
                    rec.Percentage = Value1;
                    rec.Value1 = 0;
                }
                rec.Sheet = mod.GetPaySheetByID(SheetId.ToString());
                rec.AllowName = mod.GetAllowanceNameByID(AllowId.ToString());

                var res = new PayAllowanceRepo().UpdatePayAllowance(rec, HttpContext.Session.GetString("Curruser"));
                if (res > 0)
                {
                    TempData["success"] = true;
                    TempData["message"] = mod.GetSuccessMessage();
                    return RedirectToPage("AllowanceRates");
                }
                ErrMsg = mod.GetErrorMessage();
                ErrMsgType = mod.GetErrMessageTypeError();
                return Page();
            }
            else
            {
                //new record
                var payallowance = new PayAllowance();
                _Mapper.Map(this, payallowance);

                //check if ratetype is percentage. if yes save percentage value and set fixed value to 0 else just save fixed value.
                if (RateType == "Percentage")
                {
                    payallowance.Percentage = Value1;
                    payallowance.Value1 = 0;
                }
                payallowance.Sheet = mod.GetPaySheetByID(SheetId.ToString());
                payallowance.AllowName = mod.GetAllowanceNameByID(AllowId.ToString());
                var res = new PayAllowanceRepo().CreatePayAllowance(payallowance, HttpContext.Session.GetString("Curruser"));
                if (res > 0)
                {
                    TempData["success"] = true;
                    TempData["message"] = mod.GetSuccessMessage();
                    return RedirectToPage("AllowanceRates");
                }
                ErrMsg = mod.GetErrorMessage();
                ErrMsgType = mod.GetErrMessageTypeError();
                return Page();
            }
        }
    }
}

Plumbago_Brokerage/Pages/GeneralSettings/DeductionRates.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.ViewComponents;

namespace Plumbago_Brokerage.Pages.GeneralSettings
{
    public class DeductionRatesModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public SearchFilterModel Searchfilter { get; set; }
        [BindProperty(SupportsGet = true)]
        public TableListVM TableList { get; set; }


        public void OnGet()
        {
            var mod = new ModMain();
            Searchfilter.Groupname = "gs_deductionrates";
            TableList.Groupname = "gs_deductionrates";
            Searchfilter.Paysheets = mod.PopulatePaySheets();
            TableList.payDeductions = new PayDeductionsRepo().GetPayDeductionBySearchFilter(Searchfilter);
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("DeductionRates", new { Searchfilter.From, Searchfilter.To, Searchfilter.Contains, Searchfilter.Option, Searchfilter.Paysheet });
        }
    }
}

Plumbago_Brokerage/Pages/GeneralSettings/DeductionRates_Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.Models;
using Plumbago_Brokerage.ViewComponents;

namespace Plumbago_Brokerage.Pages.GeneralSettings
{
    [BindProperties]
    public class DeductionRates_EditModel : PageModel
    {
        public long Hid { get; set; }
        public long DedId { get; set; }
        public string DedName { get; set; }
        public decimal? Value1 { get; set; }
        public decimal? Percentage { get; set; }
        public string Steps { get; set; }
        public long? GradeId { get; set; }
        public string Grade { get; set; }
        public int? SheetId { get; set; }
        public string Sheet { get; set; }
        public string ErrMsg { get; set; }
        public string ErrMsgType { get; set; }
        public string RateType { get; set; }
        public IEnumerable<SelectListItem> Paysheets { get; set; }
        public IEnumerable<SelectListItem> Deductions { get; set; }
        [BindProperty(SupportsGet = true)]
        public PageEditModel EditModel { get; set; }
        private readonly IMapper _Mapper;

        public DeductionRates_EditModel(IMapper Mapper)
        {
            _Mapper = Mapper;
        }
        public IActionResult OnGet(int? id)
        {
            var mod = new ModMain();
            //var setting = new SettingsRepo().GetCompanySettings();
            if (id != null)
            {

                var deductionrate = new PayDeductionsRepo().GetPayDeductionByID(id);
                _Mapper.Map(deductionrate, this);
                EditModel.PageTitle = $"Edit Deduction Rate: {id}";
                Deductions = mod.PopulateDeductionIDs();
                Paysheets = mod.PopulatePaySheets();
                return Page();
            }
            Deductions = mod.PopulateDeductionIDs();
            Paysheets = mod.PopulatePaySheets();
            EditModel.PageTitle = "Create new Paysheet Deduction Rate";
            return Page();

        }

        public IActionResult OnPostSave()
        {
            var mod = new ModMain();
            if (Hid > 0)
            {
                //update
                var rec = new PayDeductionsRepo().GetPayDeductionByID(Hid);
                _Mapper.Map(this, rec);
                if (RateType == "Percentage")
                {
                    rec.Percentage = Value1;
                    rec.Value1 = 0;
                }
                rec.Sheet = mod.GetPaySheetByID(SheetId.ToString());
                rec.DedName = mod.GetDeductionNameByID(DedId.ToString());
                var res = new PayDeductionsRepo().UpdatePayDeduction(rec, HttpContext.Session.GetString("Curruser"));
                if (res > 0)
                {
                    TempData["success"] = true;
                    TempData["message"] = mod.GetSuccessMessage();
                    return RedirectToPage("DeductionRates");
                }
                ErrMsg = mod.GetErrorMessage();
                ErrMsgType = mod.GetErrMessageTypeError();
                return Page();
            }
            else
            {
                //new record
                var paydeductions = new PayDeductions();
                _Mapper.Map(this, paydeductions);

                //check if ratetype is percentage. if yes save percentage value and set fixed value to 0 else just save fixed value.
                if (RateType == "Percentage")
                {
                    paydeductions.Percentage = Value1;
                    paydeductions.Value1 = 0;
                }
                paydeductions.Sheet = mod.GetPaySheetByID(SheetId.ToString());
                paydeductions.DedName = mod.GetDeductionNameByID(DedId.ToString());
                var res = new PayDeductionsRepo().CreatePayDeduction(paydeductions, HttpContext.Session.GetString("Curruser"));
                if (res > 0)
                {
                    TempData["success"] = true;
                    TempData["message"] = mod.GetSuccessMessage();
                    return RedirectToPage("DeductionRates");
                }
                ErrMsg = mod.GetErrorMessage();
                ErrMsgType = mod.GetErrMessageTypeError();
                return Page();
            }


        }
    }
}

Plumbago_Brokerage/Pages/GeneralSettings/Users.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Plumbago_Brokerage.Data;
using Plumbago_Brokerage.Models;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.ViewComponents;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Http;

namespace Plumbago_Brokerage.Pages.GeneralSettings
{
    public class UsersModel : PageModel
    {

        [BindProperty(SupportsGet = true)]
        public SearchFilterModel Searchfilter { get; set; }
        [BindProperty(SupportsGet = true)]
        public TableListVM TableList { get; set; }

        public override void OnPageHandlerExecuting(PageHandlerExecutingContext context)
        {
            if (HttpContext.Session.GetInt32("Curruserid") == null)
            {
                RedirectToPage("/Welcome/Login");
            }
        }

        public void OnGet(DateTime? From, DateTime? To, string Contains, string Option)
        {
            Searchfilter.Groupname = "adm_users";
            TableList.Groupname = "adm_users";
            TableList.Users = new UsersRepo().GetUsersBySearchFilter(Searchfilter);
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("Users", new { Searchfilter.From, Searchfilter.To, Searchfilter.Contains, Searchfilter.Option });
        }
    }
}

Plumbago_Brokerage/Pages/GeneralSettings/AllowanceRates.cshtml
@page
@model Plumbago_Brokerage.Pages.GeneralSettings.AllowanceRatesModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
           Paysheet Allowance Rates
        </h3>

    </div>

    <hr />
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />

        <a class="button primary small showloading" href="/GeneralSettings/AllowanceRates_Edit"> Create New</a>

        <button type="submit" class="button showloading small alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>
    </div>
</form>

Plumbago_Brokerage/Pages/GeneralSettings/AllowanceRates_Edit.cshtml
@page
@model Plumbago_Brokerage.Pages.GeneralSettings.AllowanceRates_EditModel
@{
}
@using Plumbago_Brokerage.Data.Global
@inject ModMain modmain
<div class="container-fluid">
    <div>
        <h3>
            @Model.EditModel.PageTitle
        </h3>

    </div>
    <hr />
    @if (Model.ErrMsg != null)
    {
        ViewData["message"] = Model.ErrMsg;
        ViewData["type"] = Model.ErrMsgType;
        <partial name="_messagepanelPartial" />
    }

</div>

<div class="border-none" data-cls-panel="rounded" data-role="panel">
    <form id="myform" method="post">


        <div class="container-fluid">
            <div class="row">
                <div class="cell-12">
                    <div class="">
                        <div data-role="accordion"
                             data-one-frame="false"
                             data-show-active="true">

                            <div class="frame active">
                                <div class="heading">Allowance Rates</div>
                                <div class="content">
                                    <div class="p-2">
                                        <input type="hidden" asp-for="Hid" />


                                        <div class="row mb-3">
                                            <label class="text-small text-bold cell-sm-1">PaySheet Group</label>
                                            <div class="cell-sm-4">

                                                <select asp-for="SheetId" class="rounded" data-role="select" asp-items="Model.Paysheets">
                                                    <option disabled value="">- select -</option>
                                                </select>


                                            </div>
                                            <div class="cell-sm-1"></div>
                                            <label class="text-small text-bold cell-sm-1">Allowance Name</label>
                                            <div class="cell-sm-4">
                                                <select asp-for="AllowId" class="rounded" data-role="select" asp-items="Model.Allowances">
                                                    <option disabled value="">- select -</option>
                                                </select>
                                            </div>

                                        </div>

                                        <div class="row mb-3">

                                            <label class="text-small text-bold cell-sm-1">Rate Type</label>
                                            <div class="cell-sm-4">

                                                <select asp-for="RateType" class="rounded" data-role="select">
                                                    <option disabled value="">- select -</option>
                                                    <option value="Fixed">Fixed</option>
                                                    <option value="Percentage">Percentage</option>

                                                </select>
                                            </div>
                                            <div class="cell-sm-1"></div>
                                            <label class="text-small text-bold cell-sm-1">Amount</label>
                                            <div class="cell-sm-4">

                                                <input data-cls-input="txtallowance" class="rounded" data-role="input" asp-for="Value1" data-prepend="₦" type="text" />

                                            </div>
                                        </div>

                                        <div class="row mb-5">
                                            <div class="table-container rounded">
                                                <table data-cls-table-top="row flex-nowrap" data-cls-search="cell-md-8" data-role="table" data-check="true" class="table striped rounded row-hover" data-check-name="SelectedIDs" data-check-col-index="0">
                                                    <thead>
                                                        <tr>
                                                            <th>#ID</th>
                                                            <th>Allowance Name</th>
                                                            <th>Paysheet</th>
                                                            <th>Submitted On</th>
                                                            <th></th>

                                                        </tr>
                                                    </thead>
                                                    <tbody>

                                                        @foreach (var emp in Model.PayAllowances)
                                                        {
                                                            <tr>
                                                                <td>@emp.Hid</td>
                                                                <td>@emp.AllowName</td>
                                                                <td>@emp.Sheet</td>
                                                                <td>@modmain.FormatDate(emp.SubmitOn.Value)</td>

                                                            </tr>
                                                        }
                                                    </tbody>

                                                </table>

                                            </div>
                                        </div>


                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="form-group">

                        <div class="text-center">
                            <span class="">
                                <a class="button alert" onclick="goBack()">Cancel</a>  <button type="submit" class="button primary" asp-page-handler="SaveAndAddNew"> <i class="fas fa-save"></i> Save and Add New </button> <button type="submit" class="button primary" asp-page-handler="Submit"> <i class="fas fa-save"></i> Submit </button>
                            </span>

                        </div>


                    </div>
                </div>


            </div>

            <div>


            </div>

        </div>
    </form>

</div>

Plumbago_Brokerage/Pages/GeneralSettings/DeductionRates.cshtml
@page
@model Plumbago_Brokerage.Pages.GeneralSettings.DeductionRatesModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
            Paysheet Deduction Rates
        </h3>

    </div>

    <hr />
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />

        <a class="button primary small showloading" href="/GeneralSettings/DeductionRates_Edit"> Create New</a>

        <button type="submit" class="button showloading small alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>
    </div>
</form>

Plumbago_Brokerage/Pages/GeneralSettings/DeductionRates_Edit.cshtml
@page
@model Plumbago_Brokerage.Pages.GeneralSettings.DeductionRates_EditModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
            @Model.EditModel.PageTitle
        </h3>

    </div>
    <hr />
    @if (Model.ErrMsg != null)
    {
        ViewData["message"] = Model.ErrMsg;
        ViewData["type"] = Model.ErrMsgType;
        <partial name="_messagepanelPartial" />
    }

</div>

<div class="border-none" data-cls-panel="rounded" data-role="panel">
    <form id="myform" method="post">


        <div class="container-fluid">
            <div class="row">
                <div class="cell-12">
                    <div class="">
                        <div data-role="accordion"
                             data-one-frame="false"
                             data-show-active="true">

                            <div class="frame active">
                                <div class="heading">Deduction Rates</div>
                                <div class="content">
                                    <div class="p-2">
                                        <input type="hidden" asp-for="Hid" />


                                        <div class="row mb-3">
                                            <label class="text-small text-bold cell-sm-1">PaySheet Group</label>
                                            <div class="cell-sm-4">

                                                <select asp-for="SheetId" class="rounded" data-role="select" asp-items="Model.Paysheets">
                                                    <option disabled value="">- select -</option>
                                                </select>


                                            </div>
                                            <div class="cell-sm-1"></div>
                                            <label class="text-small text-bold cell-sm-1">Deduction Name</label>
                                            <div class="cell-sm-4">
                                                <select asp-for="DedId" class="rounded" data-role="select" asp-items="Model.Deductions">
                                                    <option disabled value="">- select -</option>
                                                </select>
                                            </div>

                                        </div>

                                        <div class="row mb-3">

                                            <label class="text-small text-bold cell-sm-1">Rate Type</label>
                                            <div class="cell-sm-4">

                                                <select asp-for="RateType" class="rounded" data-role="select">
                                                    <option disabled value="">- select -</option>
                                                    <option value="Fixed">Fixed</option>
                                                    <option value="Percentage">Percentage</option>

                                                </select>
                                            </div>
                                            <div class="cell-sm-1"></div>
                                            <label class="text-small text-bold cell-sm-1">Amount</label>
                                            <div class="cell-sm-4">

                                                <input data-cls-input="txtallowance" class="rounded" data-role="input" asp-for="Value1" data-prepend="₦" type="text" />

                                            </div>
                                        </div>


                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="form-group">

                        <div class="text-center">
                            <span class="">
                                <a class="button alert" onclick="goBack()">Cancel</a>  <button type="submit" class="button primary" asp-page-handler="Save"> <i class="fas fa-save"></i> Submit </button>
                            </span>

                        </div>


                    </div>
                </div>


            </div>

            <div>


            </div>

        </div>
    </form>

</div>

Plumbago_Brokerage/Pages/GeneralSettings/Users.cshtml
@page
@model Plumbago_Brokerage.Pages.GeneralSettings.UsersModel

@{
    ViewData["Title"] = "Users";
}

<div class="container-fluid">
    <div>
        <h3>
            Users
        </h3>

    </div>

    <hr />
</div>

<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />
        <a class="button primary showloading" href="/Admin/Users_edit"> Create New</a>
    </div>
</form>