Plumbago_Brokerage/Pages/Payroll/BatchPayrollProcessing.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.Models;
using Plumbago_Brokerage.ViewComponents;
using PlumbagoHR.Data.Repository;

namespace Plumbago_Brokerage.Pages.Payroll
{
    [BindProperties]
    public class BatchPayrollProcessingModel : PageModel
    {
        public int Id { get; set; }
        public int? SheetId { get; set; }
        public string EmployeeId { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string Period { get; set; }
        public string Previousmonth { get; set; }
        public bool MailEmployees { get; set; }
        public bool IncludeExgratial { get; set; }
        public decimal? Basic { get; set; }
        public decimal? Dtotal { get; set; }
        public decimal? NetPay { get; set; }
        public string Confirmation { get; set; }
        public string BranchId { get; set; }
        public string DeptId { get; set; }
        public string UnitId { get; set; }
        public string Step { get; set; }
        public long? GradeId { get; set; }
        public string Grade { get; set; }
        public string EmployeeStatus { get; set; }
        public string Detail { get; set; }
        public string TransGuid { get; set; }
        public string TransStatus { get; set; }
        public IEnumerable<SelectListItem> Previousmonths { get; set; }
        public IEnumerable<SelectListItem> NextMonths { get; set; }
        public IEnumerable<SelectListItem> PaySheetGroups { get; set; }
        [BindProperty(SupportsGet = true)]
        public PageEditModel EditModel { get; set; }
        public string ErrMsg { get; set; }
        public string ErrMsgType { get; set; }
        private readonly IMapper _Mapper;

        public BatchPayrollProcessingModel(IMapper Mapper)
        {
            _Mapper = Mapper;
        }
        public IActionResult OnGet()
        {
            var mod = new ModMain();
            Previousmonths = mod.PopulatePeriod();
            NextMonths = mod.PopulateNextMonths();
            PaySheetGroups = mod.PopulatePaySheets();
            EditModel.PageTitle = $"Process Batch Payroll";
            return Page();
        }

        public IActionResult OnPostProcess()
        {
            var mod = new ModMain();
            var paysliprepo = new PaySlipRepo();
            var employeerepo = new EmployeesRepo();
            var curruser = HttpContext.Session.GetString("Curruser");
            string exgratial = IncludeExgratial ? "Y" : "N";
                var result = paysliprepo.ProcessBatchPayroll(Guid.NewGuid().ToString(), Previousmonth, Period, SheetId, curruser, exgratial);
                if (result > 0)
                {
                    if (MailEmployees == true)
                    {
                        //mail employee payslips
                        var payslips = paysliprepo.GetNextMonthPayslips(Period, SheetId);
                        if (mod.ProcessEmployeePayslipToEmail(payslips) == true)
                        {
                            TempData["success"] = true;
                            TempData["message"] = $"Batch Payroll Processed Successfuly with total: {result} records and Mail sent!";
                            return RedirectToPage("EmployeePayrollDetails", new { Period });
                        }
                        else
                        {
                            //mail not sent properly
                            TempData["success"] = true;
                            TempData["message"] = $"Batch Payroll Processed Successfuly with total: {result} records but an error occured while sending Employee mails. Contact your Administrator";
                            return RedirectToPage("EmployeePayrollDetails", new { Period });
                        }
                        
                    }
                    
                }
                ErrMsg = mod.GetErrorMessage();
                ErrMsgType = mod.GetErrMessageTypeError();
                return Page();
       
        }

        public IActionResult OnPostEmail()
        {
            var mod = new ModMain();
            var setting = new SettingsRepo().GetCompanySettings();
           
            return Page();
        }
    }

    
}

Plumbago_Brokerage/Pages/Payroll/EmployeePayroll.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.ViewComponents;
using PlumbagoHR.Data.Repository;

namespace Plumbago_Brokerage.Pages.Payroll
{
    public class Employee_PayrollModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public SearchFilterModel Searchfilter { get; set; }
        [BindProperty(SupportsGet = true)]
        public TableListVM TableList { get; set; }
        public void OnGet()
        {
            var mod = new ModMain();
            Searchfilter.Groupname = "payroll_emp_payroll";
            TableList.Groupname = "payroll_emp_payroll";
            Searchfilter.Paysheets = mod.PopulatePaySheets();
            TableList.Employees = new EmployeesRepo().GetEmployeesBySearchFilter(Searchfilter);
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("EmployeePayroll", new { Searchfilter.Contains, Searchfilter.Option, Searchfilter.Paysheet });
        }
    }
}

Plumbago_Brokerage/Pages/Payroll/EmployeePayrollDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.ViewComponents;

namespace Plumbago_Brokerage.Pages.Payroll
{
    public class EmployeePayrollDetailsModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public SearchFilterModel Searchfilter { get; set; }
        [BindProperty(SupportsGet = true)]
        public TableListVM TableList { get; set; }
        [BindProperty]
        public List<int> SelectedIDs { get; set; }
        public void OnGet()
        {
            var mod = new ModMain();
            Searchfilter.Groupname = "payroll_EmployeePayroll_Details";
            TableList.Groupname = "payroll_EmployeePayroll_Details";
            Searchfilter.Paysheets = mod.PopulatePaySheets();
            Searchfilter.Periods = mod.PopulatePeriodOld();
            TableList.Payslips = new PaySlipRepo().GetPaySlipsBySearchFilter(Searchfilter);
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("EmployeePayrollDetails", new { Searchfilter.Contains, Searchfilter.Option, Searchfilter.Paysheet, Searchfilter.Period });
        }

        public IActionResult OnPostMailPayslip(List<int> SelectedIDs)
        {
            foreach (var rec in SelectedIDs)
            {

            }
            return Page();
        }
        public IActionResult OnPostPrintPayslip(List<int> SelectedIDs)
        {
            var rec = SelectedIDs[0];

            return Page();
        }
    }
}

Plumbago_Brokerage/Pages/Payroll/EmployeePayrollDetails_Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.Models;
using Plumbago_Brokerage.ViewComponents;
using PlumbagoHR.Data.Repository;

namespace Plumbago_Brokerage.Pages.Payroll
{
    [BindProperties]
    public class EmployeePayrollDetails_EditModel : PageModel
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string Period { get; set; }
        public decimal? Basic { get; set; }
        public decimal? Dtotal { get; set; }
        public decimal? NetPay { get; set; }
  
        public string Grade { get; set; }
      
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? Atotal { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? GrossPay { get; set; }
        public decimal? HousingAllowance { get; set; }
        public decimal? TransportAllowance { get; set; }

        public List<PaySlipDetails> PayslipAllowances { get; set; }
        public List<PaySlipDetails> PayslipDeductions { get; set; }

        public IEnumerable<SelectListItem> Periods { get; set; }
        //public List<PayAllowance> Allowances { get; set; }
        //public List<PayDeductions> Deductions { get; set; }
        [BindProperty(SupportsGet = true)]
        public PageEditModel EditModel { get; set; }
        public string ErrMsg { get; set; }
        public string ErrMsgType { get; set; }
        private readonly IMapper _Mapper;

        public EmployeePayrollDetails_EditModel(IMapper Mapper)
        {
            _Mapper = Mapper;
        }
        public IActionResult OnGet(int? id)
        {
            var mod = new ModMain();
            var paysliprepo = new PaySlipRepo();
            var paydetailrepo = new PaySlipDetailRepo();
            if (id != null)
            {
                var slip = paysliprepo.GetPayslipByID(id);
                _Mapper.Map(slip, this);
                //bind payslip details
                PayslipAllowances = paydetailrepo.GetPaySlipAllowancesByPayslipID((int)id);
                PayslipDeductions = paydetailrepo.GetPaySlipDeductionsByPayslipID((int)id);
                EditModel.PageTitle = $"Employee Payroll Details: {id}";
                return Page();
            }
            TempData["error"] = true;
            TempData["message"] = "Select a Payslip first";
            return RedirectToPage("MonthlyVariance");

        }

        public IActionResult OnPostSave()
        {
            var mod = new ModMain();
            var paysliprepo = new PaySlipRepo();
            var paydetailrepo = new PaySlipDetailRepo();
            var slip = paysliprepo.GetPayslipByID(Id);
            var rec = _Mapper.Map(this, slip);
            rec.Atotal = PayslipAllowances.Sum(x => x.AllowanceAmount);
            var res = paysliprepo.UpdatePayslip(rec, HttpContext.Session.GetString("Curruser"));
            if (res > 0)
            {
                //update detail
                foreach (var allw in PayslipAllowances)
                {
                    var detail = paydetailrepo.GetPaySlipDetailByID(allw.Id);
                    int detailrs = 0;
                    detail.AllowanceAmount = allw.AllowanceAmount;
                    detailrs = new PaySlipDetailRepo().UpdatePayslipDetails(detail, HttpContext.Session.GetString("Curruser"));
                }

                foreach (var deduct in PayslipDeductions)
                {
                    var deductdetail = paydetailrepo.GetPaySlipDetailByID(deduct.Id);
                    int detailddrs = 0;
                    deductdetail.DeductionAmount = deduct.DeductionAmount;
                    detailddrs = new PaySlipDetailRepo().UpdatePayslipDetails(deductdetail, HttpContext.Session.GetString("Curruser"));
                }
                TempData["success"] = true;
                TempData["message"] = $"Payroll Details Updated for Payslip {Id}. Print the Payslip Here.";
                return RedirectToPage("EmployeePayrollDetails", new { Period });
            }
            else
            {
                ErrMsg = mod.GetErrorMessage(); ErrMsgType = mod.GetErrMessageTypeError();
                return Page();
            }

        }
    }
}

Plumbago_Brokerage/Pages/Payroll/MonthlyVariance.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.ViewComponents;


namespace Plumbago_Brokerage.Pages.Payroll
{
    public class MonthlyVarianceModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public SearchFilterModel Searchfilter { get; set; }
        [BindProperty(SupportsGet = true)]
        public TableListVM TableList { get; set; }
        public void OnGet()
        {
            var mod = new ModMain();
            Searchfilter.Groupname = "payroll_monthly_variance";
            TableList.Groupname = "payroll_monthly_variance";
            Searchfilter.Paysheets = mod.PopulatePaySheets();
            Searchfilter.Periods = mod.PopulatePeriodOld();
            TableList.Payslips = new PaySlipRepo().GetPaySlipsBySearchFilter(Searchfilter);
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("MonthlyVariance", new { Searchfilter.Contains, Searchfilter.Option, Searchfilter.Paysheet, Searchfilter.Period });
        }
    }
}

Plumbago_Brokerage/Pages/Payroll/MonthlyVariance_Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Plumbago_Brokerage.Data.Global;
using Plumbago_Brokerage.Data.Repository;
using Plumbago_Brokerage.Models;
using Plumbago_Brokerage.ViewComponents;

namespace Plumbago_Brokerage.Pages.Payroll
{
    public class MonthlyVariance_EditModel : PageModel
    {
        public int Id { get; set; }
        public int? SheetId { get; set; }
        public string EmployeeId { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string Period { get; set; }
        public decimal? Basic { get; set; }
        public decimal? Dtotal { get; set; }
        public decimal? NetPay { get; set; }
        public string Confirmation { get; set; }
        public string BranchId { get; set; }
        public string Branch { get; set; }
        public string DeptId { get; set; }
        public string UnitId { get; set; }
        public string Step { get; set; }
        public long? GradeId { get; set; }
        public string Grade { get; set; }
        public string EmployeeStatus { get; set; }
        public string Detail { get; set; }
        public string TransGuid { get; set; }
        public string TransStatus { get; set; }
        public string SubmittedBy { get; set; }
        public DateTime? SubmittedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string BatchGuid { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? Atotal { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:n}")]
        public decimal? GrossPay { get; set; }
        public decimal? HousingAllowance { get; set; }
        public decimal? TransportAllowance { get; set; }

        public List<PaySlipDetails> PayslipAllowances { get; set; }
        public List<PaySlipDetails> PayslipDeductions { get; set; }

        public IEnumerable<SelectListItem> Periods { get; set; }
        //public List<PayAllowance> Allowances { get; set; }
        //public List<PayDeductions> Deductions { get; set; }
        [BindProperty(SupportsGet = true)]
        public PageEditModel EditModel { get; set; }
        public string ErrMsg { get; set; }
        public string ErrMsgType { get; set; }
        private readonly IMapper _Mapper;

        public MonthlyVariance_EditModel(IMapper Mapper)
        {
            _Mapper = Mapper;
        }
        public IActionResult OnGet(int? id)
        {
            var mod = new ModMain();
            var paysliprepo = new PaySlipRepo();
            var paydetailrepo = new PaySlipDetailRepo();
            if (id != null)
            {
                var slip = paysliprepo.GetPayslipByID(id);               
                _Mapper.Map(slip, this);
                //bind payslip details
                PayslipAllowances = paydetailrepo.GetPaySlipAllowancesByPayslipID((int)id);
                PayslipDeductions = paydetailrepo.GetPaySlipDeductionsByPayslipID((int)id);
                EditModel.PageTitle = $"Employee Monthly Variance Details: {id}";
                return Page();
            }
            TempData["error"] = true;
            TempData["message"] = "Select a Payslip first";
            return RedirectToPage("EmployeePayrollDetails");

        }
    }
}

Plumbago_Brokerage/Pages/Payroll/ProcessPaySlipJournal.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Plumbago_Brokerage.Pages.Payroll
{
    public class ProcessPaySlipJournalModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Plumbago_Brokerage/Pages/Payroll/BatchPayrollProcessing.cshtml
@page
@model Plumbago_Brokerage.Pages.Payroll.BatchPayrollProcessingModel
@{
}

<div class="container-fluid">
    <div>
        <h3>
            @Model.EditModel.PageTitle
        </h3>

    </div>
    <hr />
    @if (Model.EditModel.ErrMsg != null)
    {
        ViewData["message"] = Model.EditModel.ErrMsg;
        ViewData["type"] = Model.EditModel.ErrMsgType;
        <partial name="_messagepanelPartial" />
    }
</div>


<div class="border-none" data-cls-panel="rounded" data-role="panel">
    <form id="myform" method="post">


        <div class="container-fluid">
            <div class="row">
                <div class="cell-12">

                    <div class="mb-3" data-role="accordion"
                         data-one-frame="false"
                         data-show-active="true">

                        <div class="frame active">
                            <div class="heading">Process Batch Payroll</div>
                            <div class="content">
                                <div class="p-2">

                                    <div class="row mb-3">
                                        <label class="text-small text-bold cell-sm-1">Previous Month</label>
                                        <div class="cell-sm-4">
                                            <select asp-for="Previousmonth" asp-items="Model.Previousmonths" class="rounded text-small" data-role="select" >
                                                <option disabled value="">- select -</option>

                                            </select>

                                        </div>
                                        <div class="cell-sm-1"></div>
                                        <label class="text-small text-bold cell-sm-1">Next Month</label>
                                        <div class="cell-sm-4">
                                            <select asp-for="Period" asp-items="Model.NextMonths" class="rounded text-small" data-role="select">
                                                <option disabled value="">- select -</option>

                                            </select>
                                        </div>

                                    </div>
                                    <div class="row mb-3">
                                        <label class="text-small text-bold cell-sm-1">Paysheet Group</label>
                                        <div class="cell-sm-4">

                                            <select asp-for="SheetId" asp-items="Model.PaySheetGroups" class="rounded text-small" data-role="select">
                                                <option disabled value="">- select -</option>
                                                <option value="0">All</option>

                                            </select>

                                        </div>
                                        <div class="cell-sm-1"></div>
                                        <label class="text-small text-bold cell-sm-1">Mail Employee PaySlips</label>
                                        <div class="cell-sm-1">
                                            <input type="checkbox" asp-for="MailEmployees" data-role="switch" data-caption="" checked>
                                        </div>
                                        <div class="cell-sm-1"></div>
                                        <label class="text-small text-bold cell-sm-1">Include Ex-Gratial?</label>
                                        <div class="cell-sm-1">
                                            <input type="checkbox" asp-for="IncludeExgratial" data-role="switch" data-caption="" >
                                        </div>

                                    </div>

                                    <div class="form-group">

                                        <div class="text-center">
                                            <span class="">
                                                <button type="submit" class="button primary" asp-page-handler="Email"> <i class="fas fa-save"></i> test email</button>
                                                <a class="button alert" onclick="goBack()">Cancel</a>  <button type="submit" class="button primary" asp-page-handler="Process"> <i class="fas fa-save"></i> Start Processing... </button>
                                            </span>

                                        </div>


                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>


                    
                    
                </div>


            </div>

            <div>


            </div>

        </div>
    </form>

</div>

Plumbago_Brokerage/Pages/Payroll/EmployeePayroll.cshtml
@page
@model Plumbago_Brokerage.Pages.Payroll.Employee_PayrollModel
@{
}

<div class="container-fluid">
    <div>
        <h3>
          New Employee Payroll
        </h3>

    </div>

    <hr />
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />

     
    </div>
</form>

Plumbago_Brokerage/Pages/Payroll/EmployeePayrollDetails.cshtml
@page
@model Plumbago_Brokerage.Pages.Payroll.EmployeePayrollDetailsModel
@{
}
<div class="container-fluid">
    <div>
        <h3>
            Employee Payroll Details
        </h3>

    </div>

    <hr />
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />

        <button type="submit" class="button primary" asp-page-handler="PrintPayslip"><i class="fas fa-print"></i> Print Payslip</button>
        <button type="submit" class="button primary" asp-page-handler="MailPayslip"><i class="fas fa-message"></i> Mail Payslip</button>

        @*<button type="submit" class="button alert"  onclick="return confirm('Are you sure you want to delete?')" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>*@
    </div>
</form>

Plumbago_Brokerage/Pages/Payroll/MonthlyVariance.cshtml
@page
@model Plumbago_Brokerage.Pages.Payroll.MonthlyVarianceModel
@{
}


<div class="container-fluid">
    <div>
        <h3>
            Employee Monthly Variance
        </h3>

    </div>

    <hr />
</div>


<form method="post">
    <div class="border-none" data-cls-panel="rounded" data-role="panel">

        <partial name="SearchFilterArea" model="Model.Searchfilter" />
        <partial name="TableAreaPartial" model="Model.TableList" />

        <button type="submit" class="button primary" asp-page-handler="PrintPayslip"><i class="fas fa-print"></i> Print Payslip</button>

        <button type="submit" class="button alert" asp-page-handler="Delete"><i class="fas fa-trash"></i> Delete</button>
    </div>
</form>

Plumbago_Brokerage/Pages/Payroll/ProcessPaySlipJournal.cshtml
@page
@model Plumbago_Brokerage.Pages.Payroll.ProcessPaySlipJournalModel
@{
}